# Generated by Django 4.2.5 on 2023-09-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.URLField(max_length=255),
        ),
    ]
