# Generated by Django 4.2.5 on 2023-10-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.URLField(max_length=2000),
        ),
    ]
