# Generated by Django 4.2.6 on 2023-10-06 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_categoryplate_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.restaurant'),
            preserve_default=False,
        ),
    ]
