# Generated by Django 4.2.6 on 2023-10-07 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_menu_alter_plate_category_alter_plate_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='img_url',
        ),
    ]
