# Generated by Django 4.2.6 on 2023-10-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_remove_menu_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='plates',
            field=models.ManyToManyField(to='server.plate'),
        ),
    ]
