# Generated by Django 4.2.6 on 2023-10-07 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_remove_plate_menu_menu_plates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='plates',
        ),
        migrations.AddField(
            model_name='plate',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.menu'),
        ),
    ]
