# Generated by Django 4.2.6 on 2023-10-07 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_remove_menu_plates_plate_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.menu')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.plate')),
            ],
            options={
                'unique_together': {('menu', 'plate')},
            },
        ),
    ]
