# Generated by Django 4.2.6 on 2023-10-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_menuplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
