# Generated by Django 4.2.5 on 2023-10-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_restaurant_isopen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='isOpen',
            new_name='is_open',
        ),
    ]
