# Generated by Django 4.2.5 on 2023-10-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_rename_isopen_restaurant_is_open'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='menuplate',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.restaurant'),
        ),
        migrations.AlterField(
            model_name='menuplate',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.menu'),
        ),
        migrations.AlterField(
            model_name='menuplate',
            name='plate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.plate'),
        ),
        migrations.AlterUniqueTogether(
            name='menuplate',
            unique_together={('menu', 'plate', 'restaurant')},
        ),
    ]
