# Generated by Django 4.2.6 on 2023-10-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_menu_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.URLField(default=None, max_length=2000),
        ),
    ]
