# Generated by Django 4.2.6 on 2023-10-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_menu_img_menu_url_alter_restaurant_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='menu_name',
        ),
    ]
