# Generated by Django 4.2.5 on 2023-11-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_role_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
