# Generated by Django 4.2.5 on 2023-11-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_user_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dni',
        ),
    ]
