# Generated by Django 4.2.5 on 2023-11-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_rename_name_menu_menu_name'),
        ('server', '0025_remove_employee_dni'),
    ]

    operations = [
    ]
