# Generated by Django 4.2.6 on 2023-11-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_merge_20231124_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='maternal_surname',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='paternal_surname',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
